databases:
  mysql: # not used
    driver: mysql
    dsn: "root:1234@tcp(localhost:3306)/goat?charset=utf8mb4&parseTime=True&loc=Local"
    config:
      max_open_conns: 20
      max_idle_conns: 10
      conn_max_lifetime: 3600 # second
      conn_max_idle_time: 600 # second
  postgres:
    driver: pgx
    dsn: "postgres://hiro:1234@localhost:5432/goat?sslmode=disable"
    config:
      max_open_conns: 30
      max_idle_conns: 15
      conn_max_lifetime: 3600 # second
      conn_max_idle_time: 600 # second
redis:
  addr: "localhost:6379"
  password: ""
  db: 0